version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-volume:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - cloud-network

  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.2
    ports:
      - '25826:25826'
    volumes:
      - /home/japca/projects/my-projects/cloud/docker/elastic/logstash.config:/elk-config/logstash.config
      - /home/japca/elastic-service.log:/elastic-service.log
    command: logstash -f /elk-config/logstash.config
    networks:
      - cloud-network
    depends_on:
      - elasticsearch

#    kibana:
#      image: docker.elastic.co/kibana/kibana:6.3.2
#      ports:
#        - '5601:5601'
#      networks:
#        - cloud-network
#      depends_on:
#        - elasticsearch


#  rabbit:
#    build:
#      context: .
#      dockerfile: docker/rabbit/Dockerfile
#    environment:
#      - RABBITMQ_DEFAULT_USER=guest
#      - RABBITMQ_DEFAULT_PASS=guest
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    networks:
#      cloud-network:
#    restart: "always"

#
#  consul:
#    image: bitnami/consul:1.4.4
#    container_name: consul
##    volumes:
##       - /programs/IdeaProjects/my-projects/cloud/consul/consul-config.json:/opt/bitnami/consul/conf/consul.json
##       - /vagrant/consul/consul1.json:/opt/bitnami/consul/conf/consul.json
##    environment:
##      - CONSUL_LOCAL_CONFIG=/opt/bitnami/consul/consul.json
##    networks:
##      - consul-network
#  consul1:
#    image: bitnami/consul:1.4.4
#    container_name: consul
#    volumes:
#      #   /   - /programs/IdeaProjects/my-projects/cloud/consul/consul.json:/opt/bitnami/consul/conf/consul.json
#      - /vagrant/consul/config1.json:/opt/bitnami/consul/conf/consul.json
#
#    #    environment:
#    #      - CONSUL_LOCAL_CONFIG=/opt/bitnami/consul/consul.json
##    networks:
##      - consul-network
##  db-service:
##    build:
##      context: db-service
##    container_name: db-service
##    ports:
##      - "8081:8080"
##    environment:
##      - SPRING_CLOUD_CONSUL_HOST=consul
##      - SERVER_NAME=${SERVER_NAME}
##    networks:
##      - consul-network
##    depends_on:
##      - consul

networks:
  cloud-network:
    driver: bridge

volumes:
  elastic-volume:
  rabbit-volume:









